"""
implementation(drupal): \Drupal\silverback_gutenberg\Directives::editorBlockChildren
"""
directive @resolveEditorBlockChildren repeatable on FIELD_DEFINITION

"""
implementation(drupal): \Drupal\silverback_gutenberg\Directives::editorBlockMarkup
"""
directive @resolveEditorBlockMarkup repeatable on FIELD_DEFINITION

"""
implementation(drupal): \Drupal\silverback_gutenberg\Directives::editorBlockMedia
"""
directive @resolveEditorBlockMedia repeatable on FIELD_DEFINITION

"""
implementation(drupal): \Drupal\silverback_gutenberg\Directives::editorBlockType
"""
directive @resolveEditorBlockType repeatable on FIELD_DEFINITION | UNION | ENUM | INTERFACE

"""
Parse a gutenberg document into block data.

implementation(drupal): \Drupal\silverback_gutenberg\Directives::editorBlocks
"""
directive @resolveEditorBlocks(
  path: String!
  ignored: [String!]
  aggregated: [String!]
) repeatable on FIELD_DEFINITION

"""
Retrieve an editor block attribute.

implementation(drupal): \Drupal\silverback_gutenberg\Directives::editorBlockAttribute
"""
directive @resolveEditorBlockAttribute(
  key: String!
  plainText: Boolean
) repeatable on FIELD_DEFINITION | UNION | INTERFACE
